version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: krawart_security
    ports:
      - "5432:5432"
    networks:
      - krawart-security

networks:
  krawart-security:
    driver: bridge