services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: krawart_security
    ports:
      - "5432:5432"
    networks:
      - network

networks:
  network:
    driver: bridge
