env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:prettier/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  space-before-function-paren: off
  react/react-in-jsx-scope: off
  prettier/prettier:
    - warn
    - endOfLine: lf
    - usePrettierrc: true



